### ISSUE TITLE
Send data from Unity to Google spreadsheet not working anymore?

### ISSUE THREAD

**Issue by twdRon** [luzan/Unity-Google-Spreadsheet#1]
No error is shown on the console. But the data I sent from Unity is not showing up on the spreadsheet.

I was working on a project and this source code is all I need to make it work.

**Comment by luzan** [comment]
Please use console.log to see if you get any errors. I'll not be able to make guess on the error unless I get one. As this code it working for other, please verify that you have made proper changes on the fields as required.

**Comment by dragologic** [comment]
I got HTTP/1.1 400 Bad Request

**Comment by PurpleReverie** [comment]
just tried out the code from your video. Its not working either. At first it was giving me 401 unauthorized error, changed it all to public. was still giving 401 for a while, but then it stopped giving that error, but responses arnt getting through. it does send back a html file with just css data though.

Has google changed their protocol

**Comment by luzan** [comment]
Sorry for late response. I just cloned the project and checked, it is working on Unity Version 2018.3.5f1.  This means there is no change in protocol. I'll try to test it with new version, and will let you know.
