### ISSUE TITLE
converting from WWW to UnityWebRequest

### ISSUE THREAD

**Issue by shacharoz** [luzan/Unity-Google-Spreadsheet#3]
hi @luzan 
i have downloaded your project and used it.
i have also converted the code to work with UnityWebRequest instead of depricated obsolete WWW.

here is the code. i would be happy if you update yours for others in the future.

**Comment by shacharoz** [comment]
[SendToGoogle.txt](https://github.com/luzan/Unity-Google-Spreadsheet/files/4807809/SendToGoogle.txt)

**Comment by shacharoz** [comment]
change the name to .cs

**Comment by luzan** [comment]
Thank you, I have updated the code.
